# ------------------------------------------------------
# | ddddd   eeeee   ccccc   eeeee   bbbbb   u   u |
# | d   d   e       c       e       b    b  u   u |
# | d   d   eeee    c       eeee    bbbbb   u   u |
# | d   d   e       c       e       b    b  u   u |
# | ddddd   eeeee   ccccc   eeeee   bbbbb   uuuuu |
# ------------------------------------------------------
# Schittenhelm â€“ Homeassistant Configuration
# File: docker-compose.yaml
# Created by: DeCeBu (Data Excellence, Connectivity and Business)
# More info: https://github.com/DeCeBu/ha_efhs
# License: CC-BY-NC-SA-4.0
# ------------------------------------------------------

services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
