# ------------------------------------------------------
# | ddddd   eeeee   ccccc   eeeee   bbbbb   u   u |
# | d   d   e       c       e       b    b  u   u |
# | d   d   eeee    c       eeee    bbbbb   u   u |
# | d   d   e       c       e       b    b  u   u |
# | ddddd   eeeee   ccccc   eeeee   bbbbb   uuuuu |
# ------------------------------------------------------
# HomeSmartHome – Homeassistant Configuration
# File: knx.yaml
# Created by: DeCeBu (Data Excellence, Connectivity and Business)
# More info: https://github.com/DeCeBu/HomeSmartHome
# ------------------------------------------------------

# Substruktur über Includes
light: !include includes/knx/knx_light.yaml
switch: !include includes/knx/knx_switch.yaml
binary_sensor: !include includes/knx/knx_binarysensor.yaml
button: !include includes/knx/knx_button.yaml
climate: !include includes/knx/knx_climate.yaml
sensor: !include includes/knx/knx_sensor.yaml
#expose: !include includes/knx/knx_expose.yaml
cover: !include includes/knx/knx_cover.yaml


