# ─────────────────────────────
# EG Bad
# ─────────────────────────────
- name: eg_bad_heizaktor
  temperature_address: "4/2/0"
  temperature_step: 0.5
  target_temperature_address: "4/2/1"
  target_temperature_state_address: "4/2/3"
  command_value_state_address: "4/2/4"
  operation_mode_address: "4/2/6"
  operation_mode_state_address: "4/2/7"

# ─────────────────────────────
# EG Bad FBH
# ─────────────────────────────
- name: eg_bad_fbh_heizaktor
  temperature_address: "4/2/10"
  temperature_step: 0.5
  target_temperature_address: "4/2/11"
  target_temperature_state_address: "4/2/13"
  command_value_state_address: "4/2/14"
  operation_mode_address: "4/2/16"
  operation_mode_state_address: "4/2/17"

# ─────────────────────────────
# EG Schlafen
# ─────────────────────────────
- name: eg_sch_heizaktor
  temperature_address: "4/2/20"
  temperature_step: 0.5
  target_temperature_address: "4/2/21"
  target_temperature_state_address: "4/2/23"
  command_value_state_address: "4/2/24"
  operation_mode_address: "4/2/26"
  operation_mode_state_address: "4/2/27"

# ─────────────────────────────
# EG Wohnen
# ─────────────────────────────
- name: eg_woh_heizaktor
  temperature_address: "4/2/30"
  temperature_step: 0.5
  target_temperature_address: "4/2/31"
  target_temperature_state_address: "4/2/33"
  command_value_state_address: "4/2/34"
  operation_mode_address: "4/2/36"
  operation_mode_state_address: "4/2/37"

# ─────────────────────────────
# OG Bad
# ─────────────────────────────
- name: og_bad_heizaktor
  temperature_address: "4/3/0"
  temperature_step: 0.5
  target_temperature_address: "4/3/1"
  target_temperature_state_address: "4/3/3"
  command_value_state_address: "4/3/4"
  operation_mode_address: "4/3/6"
  operation_mode_state_address: "4/3/7"

# ─────────────────────────────
# OG Bad FBH
# ─────────────────────────────
- name: og_bad_fbh_heizaktor
  temperature_address: "4/3/10"
  temperature_step: 0.5
  target_temperature_address: "4/3/11"
  target_temperature_state_address: "4/3/13"
  command_value_state_address: "4/3/14"
  operation_mode_address: "4/3/16"
  operation_mode_state_address: "4/3/17"

# ─────────────────────────────
# OG Gast
# ─────────────────────────────
- name: og_gas_heizaktor
  temperature_address: "4/3/40"
  temperature_step: 0.5
  target_temperature_address: "4/3/41"
  target_temperature_state_address: "4/3/43"
  command_value_state_address: "4/3/44"
  operation_mode_address: "4/3/46"
  operation_mode_state_address: "4/3/47"

# ─────────────────────────────
# OG Kueche
# ─────────────────────────────
- name: og_kue_heizaktor
  temperature_address: "4/3/30"
  temperature_step: 0.5
  target_temperature_address: "4/3/31"
  target_temperature_state_address: "4/3/33"
  command_value_state_address: "4/3/34"
  operation_mode_address: "4/3/36"
  operation_mode_state_address: "4/3/37"

# ─────────────────────────────
# OG Schlafen
# ─────────────────────────────
- name: og_sch_heizaktor
  temperature_address: "4/3/50"
  temperature_step: 0.5
  target_temperature_address: "4/3/51"
  target_temperature_state_address: "4/3/53"
  command_value_state_address: "4/3/54"
  operation_mode_address: "4/3/56"
  operation_mode_state_address: "4/3/57"

# ─────────────────────────────
# OG Wohnen
# ─────────────────────────────
- name: og_woh_heizaktor
  temperature_address: "4/3/20"
  temperature_step: 0.5
  target_temperature_address: "4/3/21"
  target_temperature_state_address: "4/3/23"
  command_value_state_address: "4/3/24"
  operation_mode_address: "4/3/26"
  operation_mode_state_address: "4/3/27"

# ─────────────────────────────
# UG Bad
# ─────────────────────────────
- name: ug_bad_heizaktor
  temperature_address: "4/1/0"
  temperature_step: 0.5
  target_temperature_address: "4/1/1"
  target_temperature_state_address: "4/1/3"
  command_value_state_address: "4/1/4"
  operation_mode_address: "4/1/6"
  operation_mode_state_address: "4/1/7"

# ─────────────────────────────
# UG Bad FBH
# ─────────────────────────────
- name: ug_bad_fbh_heizaktor
  temperature_address: "4/1/10"
  temperature_step: 0.5
  target_temperature_address: "4/1/11"
  target_temperature_state_address: "4/1/13"
  command_value_state_address: "4/1/14"
  operation_mode_address: "4/1/16"
  operation_mode_state_address: "4/1/17"

# ─────────────────────────────
# UG Flur
# ─────────────────────────────
- name: ug_flu_heizaktor
  temperature_address: "4/1/20"
  temperature_step: 0.5
  target_temperature_address: "4/1/21"
  target_temperature_state_address: "4/1/23"
  command_value_state_address: "4/1/24"
  operation_mode_address: "4/1/26"
  operation_mode_state_address: "4/1/27"

# ─────────────────────────────
# UG Schlafen
# ─────────────────────────────
- name: ug_sch_heizaktor
  temperature_address: "4/1/30"
  temperature_step: 0.5
  target_temperature_address: "4/1/31"
  target_temperature_state_address: "4/1/33"
  command_value_state_address: "4/1/34"
  operation_mode_address: "4/1/36"
  operation_mode_state_address: "4/1/37"

# ─────────────────────────────
# UG Wohnen
# ─────────────────────────────
- name: ug_woh_heizaktor
  temperature_address: "4/1/40"
  temperature_step: 0.5
  target_temperature_address: "4/1/41"
  target_temperature_state_address: "4/1/43"
  command_value_state_address: "4/1/44"
  operation_mode_address: "4/1/46"
  operation_mode_state_address: "4/1/47"

