# ─────────────────────────────
# AS Wetterstation
# ─────────────────────────────
- name: as_zen_wet_temp
  state_address: "11/0/0"
  type: temperature
  state_class: measurement
  unit_of_measurement: "°C"

- name: as_zen_wet_wind_speed
  state_address: "11/0/7"
  type: wind_speed_ms

- name: as_zen_wet_illuminance_o
  state_address: "11/0/4"
  type: illuminance

- name: as_zen_wet_illuminance_s
  state_address: "11/0/3"
  type: illuminance

- name: as_zen_wet_illuminance_w
  state_address: "11/0/2"
  type: illuminance

# ─────────────────────────────
# EG Bad
# ─────────────────────────────
- name: eg_bad_temp
  state_address: "4/2/0"
  type: temperature
  state_class: measurement
  unit_of_measurement: "°C"

- name: eg_bad_knx_temp
  state_address: "4/2/0"
  type: temperature

- name: eg_bad_setpoint_abs
  state_address: "4/2/3"
  type: temperature

- name: eg_bad_hvac_status_raw
  state_address: "4/2/7"
  type: 1byte_unsigned
  sync_state: true

# ─────────────────────────────
# EG Bad_FBH
# ─────────────────────────────
- name: eg_bad_fbh_temp
  state_address: "4/2/10"
  type: temperature
  state_class: measurement
  unit_of_measurement: "°C"

- name: eg_bad_fbh_knx_temp
  state_address: "4/2/10"
  type: temperature

- name: eg_bad_fbh_setpoint_abs
  state_address: "4/2/13"
  type: temperature

- name: eg_bad_fbh_hvac_status_raw
  state_address: "4/2/17"
  type: 1byte_unsigned
  sync_state: true

# ─────────────────────────────
# EG Schlafen
# ─────────────────────────────
- name: eg_sch_temp
  state_address: "4/2/20"
  type: temperature
  state_class: measurement
  unit_of_measurement: "°C"

- name: eg_sch_knx_temp
  state_address: "4/2/20"
  type: temperature

- name: eg_sch_setpoint_abs
  state_address: "4/2/23"
  type: temperature

- name: eg_sch_hvac_status_raw
  state_address: "4/2/27"
  type: 1byte_unsigned
  sync_state: true

# ─────────────────────────────
# EG Wohnen
# ─────────────────────────────
- name: eg_woh_temp
  state_address: "4/2/30"
  type: temperature
  state_class: measurement
  unit_of_measurement: "°C"

- name: eg_woh_knx_temp
  state_address: "4/2/30"
  type: temperature

- name: eg_woh_setpoint_abs
  state_address: "4/2/33"
  type: temperature

- name: eg_woh_hvac_status_raw
  state_address: "4/2/37"
  type: 1byte_unsigned
  sync_state: true

# ─────────────────────────────
# OG Bad
# ─────────────────────────────
- name: og_bad_temp
  state_address: "4/3/0"
  type: temperature
  state_class: measurement
  unit_of_measurement: "°C"

- name: og_bad_knx_temp
  state_address: "4/3/0"
  type: temperature

- name: og_bad_setpoint_abs
  state_address: "4/3/3"
  type: temperature

- name: og_bad_hvac_status_raw
  state_address: "4/3/7"
  type: 1byte_unsigned
  sync_state: true

# ─────────────────────────────
# OG Bad_FBH
# ─────────────────────────────
- name: og_bad_fbh_temp
  state_address: "4/3/10"
  type: temperature
  state_class: measurement
  unit_of_measurement: "°C"

- name: og_bad_fbh_knx_temp
  state_address: "4/3/10"
  type: temperature

- name: og_bad_fbh_setpoint_abs
  state_address: "4/3/13"
  type: temperature

- name: og_bad_fbh_hvac_status_raw
  state_address: "4/3/17"
  type: 1byte_unsigned
  sync_state: true

# ─────────────────────────────
# OG Gast
# ─────────────────────────────
- name: og_gas_temp
  state_address: "4/3/40"
  type: temperature
  state_class: measurement
  unit_of_measurement: "°C"

- name: og_gas_knx_temp
  state_address: "4/3/40"
  type: temperature

- name: og_gas_setpoint_abs
  state_address: "4/3/43"
  type: temperature

- name: og_gas_hvac_status_raw
  state_address: "4/3/47"
  type: 1byte_unsigned
  sync_state: true

# ─────────────────────────────
# OG Kueche
# ─────────────────────────────
- name: og_kue_temp
  state_address: "4/3/30"
  type: temperature
  state_class: measurement
  unit_of_measurement: "°C"

- name: og_kue_knx_temp
  state_address: "4/3/30"
  type: temperature

- name: og_kue_setpoint_abs
  state_address: "4/3/33"
  type: temperature

- name: og_kue_hvac_status_raw
  state_address: "4/3/37"
  type: 1byte_unsigned
  sync_state: true

# ─────────────────────────────
# OG Schlafen
# ─────────────────────────────
- name: og_sch_temp
  state_address: "4/3/50"
  type: temperature
  state_class: measurement
  unit_of_measurement: "°C"

- name: og_sch_knx_temp
  state_address: "4/3/50"
  type: temperature

- name: og_sch_setpoint_abs
  state_address: "4/3/53"
  type: temperature

- name: og_sch_hvac_status_raw
  state_address: "4/3/57"
  type: 1byte_unsigned
  sync_state: true

# ─────────────────────────────
# OG Wohnen
# ─────────────────────────────
- name: og_woh_temp
  state_address: "4/3/20"
  type: temperature
  state_class: measurement
  unit_of_measurement: "°C"

- name: og_woh_knx_temp
  state_address: "4/3/20"
  type: temperature

- name: og_woh_setpoint_abs
  state_address: "4/3/23"
  type: temperature

- name: og_woh_hvac_status_raw
  state_address: "4/3/27"
  type: 1byte_unsigned
  sync_state: true

# ─────────────────────────────
# UG Bad
# ─────────────────────────────
- name: ug_bad_temp
  state_address: "4/1/0"
  type: temperature
  state_class: measurement
  unit_of_measurement: "°C"

- name: ug_bad_knx_temp
  state_address: "4/1/0"
  type: temperature

- name: ug_bad_setpoint_abs
  state_address: "4/1/3"
  type: temperature

- name: ug_bad_hvac_status_raw
  state_address: "4/1/7"
  type: 1byte_unsigned
  sync_state: true

# ─────────────────────────────
# UG Bad_FBH
# ─────────────────────────────
- name: ug_bad_fbh_temp
  state_address: "4/1/10"
  type: temperature
  state_class: measurement
  unit_of_measurement: "°C"

- name: ug_bad_fbh_knx_temp
  state_address: "4/1/10"
  type: temperature

- name: ug_bad_fbh_setpoint_abs
  state_address: "4/1/13"
  type: temperature

- name: ug_bad_fbh_hvac_status_raw
  state_address: "4/1/17"
  type: 1byte_unsigned
  sync_state: true

# ─────────────────────────────
# UG Flur
# ─────────────────────────────
- name: ug_flu_temp
  state_address: "4/1/20"
  type: temperature
  state_class: measurement
  unit_of_measurement: "°C"

- name: ug_flu_knx_temp
  state_address: "4/1/20"
  type: temperature

- name: ug_flu_setpoint_abs
  state_address: "4/1/23"
  type: temperature

- name: ug_flu_hvac_status_raw
  state_address: "4/1/27"
  type: 1byte_unsigned
  sync_state: true

# ─────────────────────────────
# UG Schlafen
# ─────────────────────────────
- name: ug_sch_temp
  state_address: "4/1/30"
  type: temperature
  state_class: measurement
  unit_of_measurement: "°C"

- name: ug_sch_knx_temp
  state_address: "4/1/30"
  type: temperature

- name: ug_sch_setpoint_abs
  state_address: "4/1/33"
  type: temperature

- name: ug_sch_hvac_status_raw
  state_address: "4/1/37"
  type: 1byte_unsigned
  sync_state: true

# ─────────────────────────────
# UG Wohnen
# ─────────────────────────────
- name: ug_woh_temp
  state_address: "4/1/40"
  type: temperature
  state_class: measurement
  unit_of_measurement: "°C"

- name: ug_woh_knx_temp
  state_address: "4/1/40"
  type: temperature

- name: ug_woh_setpoint_abs
  state_address: "4/1/43"
  type: temperature

- name: ug_woh_hvac_status_raw
  state_address: "4/1/47"
  type: 1byte_unsigned
  sync_state: true

